# Generated by Django 5.1.3 on 2024-11-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payments_link_payments_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscription',
        ),
    ]
