# Generated by Django 5.1.3 on 2024-11-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_lesson_owner'),
        ('users', '0007_remove_subscriptions_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='paid_lesson',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='paid_course',
        ),
        migrations.AddField(
            model_name='payments',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='education.course', verbose_name='Оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, help_text='Укажите ссылку на оплату', max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Введите сумму оплаты', null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, help_text='Введите id сессии для оплаты', max_length=255, null=True, verbose_name='Id сессии'),
        ),
    ]
