# Generated by Django 5.1.3 on 2024-11-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Введите цену курса', max_digits=10, verbose_name='Цена курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Введите цену урока', max_digits=10, verbose_name='Цена урока'),
        ),
    ]
